# Generated by Django 4.2.5 on 2023-09-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=15, unique=True)),
                ('percentual_minimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentual_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(through='vendas.ItemVenda', to='produtos.produto'),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
