# Generated by Django 4.2.5 on 2023-09-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_configuracaocomissao_alter_itemvenda_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocomissao',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='configuracaocomissao',
            name='percentual_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='configuracaocomissao',
            name='percentual_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
