# Generated by Django 4.2.5 on 2023-09-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dados_pessoais',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pessoas.dadospessoais'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='dados_pessoais',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pessoas.dadospessoais'),
        ),
    ]
