# Generated by Django 4.2.5 on 2023-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_dadospessoais_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dados_pessoais',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='dados_pessoais',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='telefone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.DeleteModel(
            name='DadosPessoais',
        ),
    ]
